from time import sleep
from userbot import CMD_HELP
from userbot.events import register


@register(outgoing=True, pattern='^.mantan(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(2)
    await typew.edit("`HAI MANTAN 🙂`")
    sleep(2)
    await typew.edit("`AKHIRNYA KITA BISA YAA`")
    sleep(2)
    await typew.edit("`AKHIRNYA KITA BISA SAMPAI TITIK`")
    sleep(2)
    await typew.edit("`DIMANA MELIHATMU SUDAH TIDAK SPESIAL LAGI`")
    sleep(2)
    await typew.edit("`JANGAN SALAHIN SIAPA SIAPA YA`")
    sleep(2)
    await typew.edit("`MENGENAL KAMU BUKANLAH SUATU KESALAHAN`")
    sleep(2)
    await typew.edit("`MUNGKIN TAKDIR BERKATA LAIN`")
    sleep(2)
    await typew.edit("`ALLAH TAU APA YG KITA BUTUHKAN`")
    sleep(2)
    await typew.edit("`BUKAN APA YG KITA INGINKAN `")
    sleep(2)
    await typew.edit("`TETAP SEMANGAT YAA`")
    sleep(3)
    await typew.edit("`😁`")
    sleep(2)
    await typew.edit("`BELAJAR DARI SEBUAH KESALAHAN`")
    sleep(2)
    await typew.edit("`😂`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.sedih(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`AKU SEDIH LOH `")
    sleep(1)
    await typew.edit("`GA PERNAH SLIPKOLAN`")
    sleep(1)
    await typew.edit("`🥺🥺🥺`")
    sleep(1)
    await typew.edit("`🥺🥺`")
    sleep(1)
    await typew.edit("`😭🙃`")
    sleep(1)
    await typew.edit("`😭😭😭😭`")
    sleep(1)
    await typew.edit("`GADA YG MAU SAMA GUA 😔`")
    sleep(1)
    await typew.edit("`TOLONG HAMBA YALLAH 🥺`")
    sleep(1)
    await typew.edit("`🙂🙃😭`")
    sleep(1)
    await typew.edit("`🥺BISMILLAH SLEEPCALL 🥺`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.salam(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Bismillah semoga diterima salamnya`")
    sleep(1)
    await typew.edit("`Assalammuallaikum😊😊`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.jawab(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Eh lupa jawab salam maaf atuh`")
    sleep(1)
    await typew.edit("`Walaikumsalam😊`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.pantun$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        sleep(2)
        await e.edit("MAKAN TAPE")
        sleep(2)
        await e.edit("CAMPUR KEDONDONG")
        sleep(2)
        await e.edit("PE")
        sleep(2)
        await e.edit("SENGGOL DONG")
        sleep(2)
        await e.edit("1 GRUP LAWAN GUA")
        sleep(2)
        await e.edit("CUPU")
        sleep(2)
        await e.edit("KENA MENTAL YAA CUK")
        sleep(2)
        await e.edit("MASAK AER")
        sleep(2)
        await e.edit("BIAR MATENG")
        sleep(2)
        await e.edit("MASAK AER")
        sleep(1)
        await e.edit("BIAR MATENG")
        sleep(2)
        await e.edit("JAMILAH MAKAN BAKWAN")
        sleep(2)
        await e.edit("DAHLAH GADA LAWAN")
        sleep(2)
        await e.edit("AWOKAWOKAWOK KABUR AH")
        sleep(1)
        await e.edit("KENA MENTAL GAES")
        sleep(1)
        await e.edit("BABAAAAAAÀYYYY")
        sleep(1)
        await e.edit("🥳")
        sleep(1)
        await e.edit("😎")
        sleep(1)
        await e.edit("🤡")
        sleep(2)
        await e.edit("😏")
        sleep(1)
        await e.edit("1")
        sleep(1)
        await e.edit("2")
        sleep(1)
        await e.edit("3")
        sleep(1)
        await e.edit("MENGHILANG TWING")
# Create by myself @localheart


@register(outgoing=True, pattern='^.galau(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(2)
    await typew.edit("`SAD BANGET GUA 😔 `")
    sleep(2)
    await typew.edit("`DI CUEKIN MULU🥺`")
    sleep(2)
    await typew.edit("`GADA YG MAU SAMA GUA😭 `")
    sleep(2)
    await typew.edit("`DI GHOSTING SERING🙁 `")
    sleep(2)
    await typew.edit("`PC ORANG DI READ DOANG☹ `")
    sleep(2)
    await typew.edit("`CARI SLIPKOLAN GADA YG MAU 😟`")
    sleep(2)
    await typew.edit("`APA HARUS OPERASI PLASTIK?? 😔 `")
    sleep(2)
    await typew.edit("`DAHLA MALES 😔`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.sad(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` MARI KITA NANGIS-NANGIS BUAT YANG LAGI PATAH HATI/BROKENHOME `")
    sleep(2)
    await typew.edit("`1`")
    sleep(2)
    await typew.edit("` 2 `")
    sleep(2)
    await typew.edit("` 3 `")
    sleep(2)
    await typew.edit("` 🥺 `")
    sleep(2)
    await typew.edit("`😭`")
    sleep(2)
    await typew.edit("`🥺`")
    sleep(2)
    await typew.edit("`😭`")
# Create by myself @localheart


@register(outgoing=True, pattern='^razia(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` 🏍️ `")
    sleep(1)
    await typew.edit("`ADA POLISI`")
    sleep(1)
    await typew.edit("` 🚓 `")
    sleep(1)
    await typew.edit("` WIU WIU`")
    sleep(1)
    await typew.edit("` 🚓 `")
    sleep(2)
    await typew.edit("`🚑`")
    sleep(1)
    await typew.edit("`🚓`")
    sleep(1)
    await typew.edit("`🚥 Yah Ketangkap`")
# Create by myself @localheart


@register(outgoing=True, pattern='^/wkwk(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` 😂 `")
    sleep(1)
    await typew.edit("`🤣`")
    sleep(1)
    await typew.edit("` 😁 `")
    sleep(1)
    await typew.edit("` 😅`")
    sleep(1)
    await typew.edit("`😄`")
    sleep(2)
    await typew.edit("`😀`")
    sleep(1)
    await typew.edit("`😆`")
    sleep(1)
    await typew.edit("`😓`")
# Create by myself @localheart


@register(outgoing=True, pattern='^melamar(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` AKU ADALAH KAMU  `")
    sleep(1)
    await typew.edit("`AKU INGIN MENJADI TEMAN HIDUP UNTUKMU`")
    sleep(2)
    await typew.edit("` MAU GAK KALAU GAK MAU AKU TARIK LAGI KATA NYA `")
    sleep(2)
    await typew.edit("`KALAU MAU MAH TROBOS AJA`")
    sleep(3)
    await typew.edit("`😄`")
    sleep(2)
    await typew.edit("`BISMILAH`")
    sleep(3)
    await typew.edit("`KUCINTAI DIRIMU SEKARANG DENGAN SAH`")
    sleep(1)
    await typew.edit("`DILAN 1990`")
# Create by myself @localheart


@register(outgoing=True, pattern='^buaya(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`KAMU MAU LIHAT BUAYA `")
    sleep(1)
    await typew.edit("`INISIAL R 🐊`")
    sleep(1)
    await typew.edit("` INISIAL V 🦎 `")
    sleep(1)
    await typew.edit("`INISIAL I 👌`")
    sleep(1)
    await typew.edit("`INISIAL D 🐊🦎`")
    sleep(2)
    await typew.edit("`C 🐊 DARAT`")
    sleep(1)
    await typew.edit("`U🦎 LAUT`")
    sleep(1)
    await typew.edit("`ITULAH BUAYA BUAYA HATI HATI YA 😁`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.yang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("` Sayang udah makan? `")
    sleep(1)
    await typew.edit("`Apa Kabar mu`")
    sleep(1)
    await typew.edit("` Kuharap  `")
    sleep(1)
    await typew.edit("` kau`")
    sleep(1)
    await typew.edit("`Baik-baik saja`")
    sleep(2)
    await typew.edit("`Aku sayang kamu`")
    sleep(1)
    await typew.edit("`Tapi kamu nya tidak`")
    sleep(1)
    await typew.edit("`Semoga engkau baik baik saja meski tak kumiliki.`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.raziamasker(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`ADA SATPOL PP LARI.....`")
    sleep(1)
    await typew.edit("`WOI SATPOL PP MASKER KALIAN !!`")
    sleep(1)
    await typew.edit("`🏃                        🚓`")
    await typew.edit("`🏃                       🚓`")
    await typew.edit("`🏃                      🚓`")
    await typew.edit("`🏃                     🚓`")
    await typew.edit("`🏃   `LARII`          🚓`")
    await typew.edit("`🏃                   🚓`")
    await typew.edit("`🏃                  🚓`")
    await typew.edit("`🏃                 🚓`")
    await typew.edit("`🏃                🚓`")
    await typew.edit("`🏃               🚓`")
    await typew.edit("`🏃              🚓`")
    await typew.edit("`🏃             🚓`")
    await typew.edit("`🏃            🚓`")
    await typew.edit("`🏃           🚓`")
    await typew.edit("`🏃LUMAYAN CAPEK😪   🚓`")
    await typew.edit("`🏃  LANJUT LARI         🚓`")
    await typew.edit("`🏃            🚓`")
    await typew.edit("`🏃             🚓`")
    await typew.edit("`🏃              🚓`")
    await typew.edit("`🏃               🚓`")
    await typew.edit("`🏃     SALTO DULU          🚓`")
    await typew.edit("`🏃                 🚓`")
    await typew.edit("`🏃                  🚓`")
    await typew.edit("`🏃                   🚓`")
    await typew.edit("`🏃                    🚓`")
    await typew.edit("`🏃                     🚓`")
    await typew.edit("`🏃  Huh-Huh           🚓`")
    await typew.edit("`🏃                   🚓`")
    await typew.edit("`🏃                  🚓`")
    await typew.edit("`🏃                 🚓`")
    await typew.edit("`🏃                🚓`")
    await typew.edit("`🏃               🚓`")
    await typew.edit("`🏃              🚓`")
    await typew.edit("`🏃             🚓`")
    await typew.edit("`🏃            🚓`")
    await typew.edit("`🏃           🚓`")
    await typew.edit("`🏃          🚓`")
    await typew.edit("`🏃         🚓`")
    await typew.edit("`CAPE BANGET !!!`")
    sleep(1)
    await typew.edit("`🏃       🚓`")
    await typew.edit("`🏃      🚓`")
    await typew.edit("`🏃     🚓`")
    await typew.edit("`🏃    🚓`")
    await typew.edit("`Dahlah Pasrah Aja`")
    sleep(1)
    await typew.edit("`🧎🚓🚓 KETANGKAP KAUKAN MANA MASKERNYA`")
    sleep(2)
    await typew.edit("`🤦TINGGAL DIRUMAH PAK`")
# Create by myself @localheart


@register(outgoing=True, pattern="^.ngabuburit$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("BOSEN GAK ADA KEGIATAN")
        sleep(1)
        await e.edit("DIRUMAH MULU")
        sleep(1)
        await e.edit("SEKOLAH DILIBURKAN")
        sleep(1)
        await e.edit("TEMEN GADA")
        sleep(1)
        await e.edit("`MENDING JALAN JALAN`")
        sleep(1)
        await e.edit("SAMBIL NGABUBURIT SEMOGA GADA RAZIA YA:)")
        sleep(1)
        await e.edit("...........................🚐")
        await e.edit("..........................🚐.")
        await e.edit("..............🛺.........🚐..")
        await e.edit("..............🛺........🚐...")
        await e.edit("..............🛺.......🚐....")
        await e.edit("..............🛺......🚐.....")
        await e.edit("..............🛺.....🚐......")
        await e.edit("..............🛺....🚐.......")
        await e.edit("..............🛺...🚐........")
        await e.edit("..............🛺.🚐..........")
        await e.edit("..............🛺🚐...........")
        await e.edit("............🚐🛺.............")
        await e.edit("..........🚐...🛺............")
        await e.edit(".........🚐.....🛺...........")
        await e.edit("........🚐.......🛺..........")
        await e.edit(".......🚐..........🛺........")
        await e.edit("......🚐.............🛺......")
        await e.edit(".....🚐...............🛺.....")
        await e.edit("....🚐..................🛺...")
        await e.edit("..🚐.....................🛺..")
        await e.edit(".🚐........................🛺")
        await e.edit("🚐...........................")
        await e.edit("...........................🚐")
        await e.edit("........🏠🏡🏘️............🚐.")
        await e.edit("........🏘️🏡🏠...........🚐..")
        await e.edit("........🏘️🏡🏠..........🚐...")
        await e.edit("........🏘️🏡🏠.........🚐....")
        await e.edit("........🏘️🏘️🏘️........🚐.....")
        await e.edit("........🏡🏠🏡.......🚐......")
        await e.edit("........🏘️🏡🏠......🚐.......")
        await e.edit("........🏘️🏡🏠.....🚐........")
        await e.edit("........🏘️🏡🏠....🚐.........")
        await e.edit("........🏘️🏡🏠...🚐..........")
        await e.edit("........🏘️🏡🏠..🚐...........")
        await e.edit("........🏘️🏡🏠.🚐............")
        await e.edit("........🏘️🏡🏠🚐.............")
        await e.edit("........🏘️🏡🚐🏠.............")
        await e.edit("........🏘️🚐🏡🏠.............")
        await e.edit("........🚐🏠🏡🏘️.............")
        await e.edit(".......🚐.🏠🏡🏡.............")
        await e.edit("......🚐..🏘️🏡🏠.............")
        await e.edit(".....🚐...🏘️🏡🏠.............")
        await e.edit("....🚐....🏘️🏠🏡.............")
        await e.edit("...🚐.....🏠🏡🏘️.............")
        await e.edit("..🚐......🏘️🏡🏠.............")
        await e.edit(".🚐.......🏘️🏡🏠.............")
        await e.edit("🚐........🏠🏡🏘️.............")
        await e.edit("...........................🚐")
        await e.edit("............🕌............🚐.")
        await e.edit("............🕌...........🚐..")
        await e.edit("............🕌..........🚐...")
        await e.edit("............🕌.........🚐....")
        await e.edit("............🕌........🚐.....")
        await e.edit("............🕌.......🚐......")
        await e.edit("............🕌......🚐.......")
        await e.edit("............🕌.....🚐........")
        await e.edit("............🕌....🚐.........")
        await e.edit("............🕌...🚐..........")
        await e.edit("............🕌..🚐...........")
        await e.edit("............🕌.🚐............")
        await e.edit("............🕌🚐.............")
        await e.edit("............🚐🕌.............")
        await e.edit("...........🚐.🕌.............")
        await e.edit("..........🚐..🕌.............")
        await e.edit(".........🚐...🕌.............")
        await e.edit("........🚐....🕌ᴬᴸᴸᴬᴴᵁ ᴬᴷᴮᴬᴿ²ˣ.")
        await e.edit("ᵂᴬᴴ ᴬᴰᶻᴬᴺ🚐....🕌.............")
        await e.edit("ˢᴴᴼᴸᴬᵀ ᴬᴴ🚐....🕌.............")
        await e.edit(".........🚐...🕌............")
        await e.edit("...........🚐.🕌............")
        await e.edit("............🚐🕌............")
        sleep(1)
        await e.edit("CERITANYA LAGI SHOLAT")
        sleep(1)
        await e.edit("KARNA SI DARA MAU MENAMBAH PAHALA")
        sleep(1)
        await e.edit("DIA PUN SHALAT")
        sleep(1)
        await e.edit("KATA SI DARA")
        sleep(1)
        await e.edit("SHOLAT LAH SEBELUM KAU DI SHOLATKAN")
        sleep(1)
        await e.edit("Lagi shalat🚐🕌.............")
        await e.edit("Lagi shalat..........🚐.🕌.............")
        await e.edit("...............🚐..🕌.............")
        await e.edit("..............🚐...🕌.............")
        await e.edit(".............🚐....🕌.............")
        await e.edit("............🚐.....🕌.............")
        await e.edit("...........🚐......🕌.............")
        await e.edit("..........🚐.......🕌.............")
        await e.edit("🏘️.......🚐........🕌.............")
        await e.edit("🏘️......🚐.........🕌.............")
        await e.edit("🏘️.....🚐..........🕌.............")
        await e.edit("🏘️....🚐...........🕌.............")
        await e.edit("🏘️...🚐............🕌.............")
        await e.edit("🏘️..🚐.............🕌.............")
        await e.edit("🏘️.🚐..............🕌.............")
        await e.edit("🏘️🚐...............🕌.............")
        await e.edit("..............................🚐🏘️")
        await e.edit(".............................🚐.🏘️")
        sleep(1)
        await e.edit("...........DIPERJALANAN ADA JUALAN ES CENDOL................🚐..🏘️")
        sleep(1)
        await e.edit(".............BELI ES CENDOL AH ..............🚐...🏘️")
        sleep(1)
        await e.edit("..........................🚐....🏘️")
        await e.edit(".........................🚐.....🏘️")
        await e.edit("........................🚐......🏘️")
        await e.edit(".......................🚐.......🏘️")
        await e.edit(".....................🚐.........🏘️")
        await e.edit("....................🚐..........🏘️")
        await e.edit("...................🚐...........🏘️")
        await e.edit("..................🚐............🏘️")
        await e.edit(".................🚐.............🏘️")
        await e.edit("................🚐..............🏘️")
        await e.edit("...............🚐...............🏘️")
        await e.edit("..............🚐................🏘️")
        await e.edit(".............🚐.................🏘️")
        await e.edit("............🚐..................🏘️")
        await e.edit("...........🚐...................🏘️")
        await e.edit("..........🚐....................🏘️")
        await e.edit(".........🚐.....................🏘️")
        await e.edit("........🚐......................🏘️")
        await e.edit(".......🚐.......................🏘️")
        await e.edit("......🚐........................🏘️")
        await e.edit(".....🚐.........................🏘️")
        await e.edit("....🚐..........................🏘️")
        await e.edit("...🚐...........................🏘️")
        await e.edit("..🚐............................🏘️")
        await e.edit(".🚐.............................🏘️")
        await e.edit("🚐..............................🏘️")
        await e.edit("SEBELUM SAMPAI RUMAH EH MALAH KECELAKAAN")
# Create by myself @localheart

CMD_HELP.update({
    "alphakata-kata":
    "📚 **Cmd** : `.yang`\
    \n📄 **Descriptions** : apa kabarmu sayang.\
    \n\n📚 **Cmd** : `.sayang`\
    \n📄 **Descriptions** : untuk jadi buaya.\
    \n\n📚 **Cmd** : .`buaya`\
    \n📄 **Descriptions** : contoh inisial buaya.\
    \n\n📚 **Cmd** : .`melamar`\
    \n📄 **Descriptions** : kata kata dilan.\
    \n\n📚 **Cmd** : .`wkwk`\
    \n📄 **Descriptions** : Tertawa emot.\
    \n\n📚 **Cmd** : .`razia`\
    \n📄 **Descriptions** :bada razia😂.\
    \n\n📚 **Cmd** : `.sad`\
    \n📄 **Descriptions** : sedihnya oalah.\
    \n\n📚 **Cmd** : `.galau`\
    \n📄 **Descriptions** : galau lah situ.\
    \n\n📚 **Cmd** : `.mantan`\
    \n📄 **Descriptions** : teringat mantan.\
    \n\n📚 **Cmd** : `.raziamasker.`\
    \n📄 **Descriptions** : Razia masker.\
    \n\n📚 **Cmd** : `.ngabuburit`.\
    \n📄 **Descriptions** : Ngabuburit."
})
